### ISSUE TITLE
NuGet package install error

### ISSUE THREAD

**Issue by iambigred** [salarcode/kendoHelpers#1]
I can't seem to install using NuGet:

PM>  Install-Package Salar.kendoHelpers
Attempting to gather dependencies information for package 'Salar.kendoHelpers.1.3.0' with respect to project 'telephony.web', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'Salar.kendoHelpers.1.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Salar.kendoHelpers.1.3.0'
Resolved actions to install package 'Salar.kendoHelpers.1.3.0'
Install failed. Rolling back...
Package 'Salar.kendoHelpers.1.3.0 : ' does not exist in project 'telephony.web'
Package 'Salar.kendoHelpers.1.3.0 : ' does not exist in folder 'C:\Users\user\Documents\Visual Studio 2015\Projects\telephony\packages'
Install-Package : Could not install package 'Salar.kendoHelpers 1.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:2
-  Install-Package Salar.kendoHelpers
-  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by salarcode** [comment]
With version 1.4 this bug should be fixed.
